typography_spectrum: 0.5691971681080759
color:
  brandStrength: 0.611875441391021
  lightness: 0.03175160498358309
  saturation: 0.40954951476305723
  rhythmicContrast: 0.12127880123443902
  brandColors:
    - '#2B3A42'
    - '#3F5765'
    - '#BDD4DE'
    - '#EFEFEF'
    - '#FF530D'
layout_spectrum: 0.8581042161677033
author:
  name: Paul Welling
  email: pwelling@coach.emyth.com
name: ACT business coaching
title: Grow Your Business by Acknowledging Choosing and Transforming
